const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const ts=require('typescript');
const root=path.resolve(__dirname,'..');
function load(file,deps={},env={}){const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module,exports:module.exports,process:{env},console,require(n){if(Object.hasOwn(deps,n))return deps[n];throw Error('Unexpected import '+n);}});return module.exports;}
const area=load('lib/delivery-area.ts');const pricing=load('lib/fulfillment-pricing.ts');
const serverCart=load('lib/server-cart.ts',{'@supabase/supabase-js':{createClient(){throw Error('Real database must not be used');}},'./quote':{}});
const id='11111111-1111-4111-8111-111111111111';
function fixture(fulfillment,patch={},hasId=true){let created=0;let alerts=0;let customerAlerts=0;let saved;const db={from(table){if(table==='pending_id_uploads')return{select(){return this},eq(){return this},maybeSingle:async()=>({data:hasId?{request_id:id,storage_path:'test/id.jpg',created_at:new Date().toISOString()}:null}),delete(){return{eq:async()=>({error:null})}}};if(table==='orders')return{update(){return this},eq(){return this},select(){return this},single:async()=>({data:saved,error:null})};throw Error('Unexpected table');},async rpc(name,args){assert.equal(name,'create_customer_order');created++;saved={id,order_number:'TEST',tracking_token:'TEST-TOKEN',subtotal:args.p_expected_subtotal,fulfillment:args.p_fulfillment,delivery_fee:pricing.deliveryFee(args.p_fulfillment),total:pricing.orderTotal(args.p_expected_subtotal,args.p_fulfillment)};return{error:null}}};
const route=load('app/api/orders/route.ts',{'@/lib/customer-order-email': { notifyCustomerOfOrder: async (order,email) => { assert.equal(order.tracking_token,'TEST-TOKEN'); assert.equal(email,'test@example.com'); customerAlerts++; return 'failed'; } }, '@/lib/owner-order-email': { notifyOwnerOfOrder: async () => { alerts++; return 'failed'; } }, '@/lib/delivery-area':area,'@/lib/shipping-policy':{shippingIsApproved:()=>false},'@/lib/rate-limit':{enforceRateLimit:async()=>null},'next/server':{NextResponse:{json:Response.json}},'@/lib/admin-db':{adminDatabase:()=>db},'@/lib/server-cart':{...serverCart,freshQuote:async items=>({canCheckout:true,subtotal:10,items:items.map(i=>({...i,priceChanged:false}))})}},{ENABLE_ORDER_REQUESTS:'true'});
const body={requestId:id,customerName:'Test User',customerEmail:'test@example.com',customerPhone:'9195550100',dateOfBirth:'1990-01-01',ageConfirmed:true,paymentMethod:'cashapp',fulfillment,deliveryAddress:'123 Test Street, Raleigh NC 27601',deliveryState:'NC',deliveryZip:'27601',expectedSubtotalCents:1000,deliveryFee:0,items:[{lineId:id,productId:id,variantId:null,quantity:1,price:10,fulfillment}],...patch};
return{run:()=>route.POST({json:async()=>body}),created:()=>created,alerts:()=>alerts,customerAlerts:()=>customerAlerts};}
test('meetup completes route with no delivery fee',async()=>{const f=fixture('pickup');const r=await f.run();assert.equal(r.status,201);const b=await r.json();assert.equal(b.order.total,10);assert.equal(b.order.delivery_fee,0);assert.equal(b.idReviewStatus,'pending');assert.equal(b.identityAgeVerified,false);assert.equal(f.created(),1);assert.equal(f.alerts(),1);assert.equal(f.customerAlerts(),1);});
test('approved local delivery completes route with 4.99 fee despite client zero',async()=>{const f=fixture('delivery');const r=await f.run();assert.equal(r.status,201);const b=await r.json();assert.equal(b.order.total,14.99);assert.equal(b.order.delivery_fee,4.99);assert.equal(f.created(),1);assert.equal(f.alerts(),1);assert.equal(f.customerAlerts(),1);});
test('outside area and forged state/ZIP fail before creation',async()=>{for(const patch of [{deliveryZip:'27701'},{deliveryState:'CA'},{deliveryZip:'27601-extra'},{deliveryState:'NC-extra'}]){const f=fixture('delivery',patch);assert.equal((await f.run()).status,400);assert.equal(f.created(),0);assert.equal(f.alerts(),0);assert.equal(f.customerAlerts(),0);}});
test('missing ID, underage and missing age confirmation cannot create meetup or delivery orders',async()=>{for(const method of ['pickup','delivery']){for(const [patch,hasId] of [[{},false],[{dateOfBirth:'2020-01-01'},true],[{ageConfirmed:false},true]]){const f=fixture(method,patch,hasId);assert.equal((await f.run()).status,400);assert.equal(f.created(),0);assert.equal(f.alerts(),0);assert.equal(f.customerAlerts(),0);}}});

test('unsupported and missing payment methods cannot create orders',async()=>{for(const paymentMethod of ['apple','card',null,undefined]){const f=fixture('pickup',{paymentMethod});assert.equal((await f.run()).status,400);assert.equal(f.created(),0);}});
